apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: patient-api-nginx
  namespace: easy-nginx
  labels:
    app: patient-api-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: patient-api-nginx
  template:
    metadata:
      labels:
        app: patient-api-nginx
    spec:
      containers:
      - name: patient-api-nginx-nginx
        # ✅ Remove Helm template syntax - image updater will handle this
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 30s}
      - setWeight: 75
      - pause: {duration: 30s}
      - setWeight: 100