apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: prod-secured-pipeline-ci-
  namespace: argo
spec:
  entrypoint: main-pipeline
  serviceAccountName: workflow-executor

  arguments:
    parameters:
    - name: git-repo
      value: https://github.com/vasplustechnologies/easy-nginx-demosite.git
    - name: git-branch
      value: main
    - name: image-version
      value: "1.0.0"

  templates:
  - name: main-pipeline
    steps:
    - - name: get-next-version
        template: get-next-version
    
    - - name: clone-repo
        template: git-clone

    - - name: build-image
        template: kaniko-build-push
        arguments:
          parameters:
          - name: git-sha
            value: "{{steps.clone-repo.outputs.parameters.git-sha}}"
          - name: image-version
            value: "{{steps.get-next-version.outputs.parameters.next-version}}"

    - - name: security-scan
        template: security-scan
        arguments:
          parameters:
          - name: image-tag
            value: "mofwili/easy-nginx:{{steps.build-image.outputs.parameters.semantic-tag}}"
        when: "{{steps.build-image.status}} == Succeeded"

    - - name: notify-success
        template: slack-notification
        arguments:
          parameters:
          - name: status
            value: "success"
          - name: message
            value: "🚀 CI Pipeline completed! Image: mofwili/easy-nginx:{{steps.build-image.outputs.parameters.semantic-tag}} | Scan: {{steps.security-scan.outputs.parameters.scan-result}}"
        when: "{{steps.security-scan.status}} == Succeeded"

  # FIXED VERSION: Checks Docker Hub for latest version
  - name: get-next-version
    container:
      image: curlimages/curl:latest
      command: [sh, -c]
      args:
      - |
        set -e
        echo "🔍 Determining next semantic version..."
        
        # Get ALL version tags from Docker Hub and find the latest
        echo "📡 Checking Docker Hub for existing versions..."
        LATEST_VERSION=$(curl -s "https://hub.docker.com/v2/repositories/mofwili/easy-nginx/tags/?page_size=100" | \
          grep -o '"name":"[0-9]*\.[0-9]*\.[0-9]*"' | \
          cut -d'"' -f4 | \
          sort -V | \
          tail -1) || true
        
        if [ -n "$LATEST_VERSION" ] && [ "$LATEST_VERSION" != "null" ]; then
          echo "📊 Found latest version in Docker Hub: $LATEST_VERSION"
          CURRENT_VERSION="$LATEST_VERSION"
        else
          # Fallback to workflow parameter if no versions found
          CURRENT_VERSION="{{workflow.parameters.image-version}}"
          echo "⚠️  No existing versions found in Docker Hub, using default: $CURRENT_VERSION"
        fi
        
        # Parse and increment version
        MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
        MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
        PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
        
        # Increment patch version
        NEW_PATCH=$((PATCH + 1))
        NEXT_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        
        echo "🎯 Version increment: $CURRENT_VERSION → $NEXT_VERSION"
        echo $NEXT_VERSION > /tmp/next-version.txt
      volumeMounts:
      - name: workspace-pvc
        mountPath: /mnt/workspace
    outputs:
      parameters:
      - name: next-version
        valueFrom:
          path: /tmp/next-version.txt

  - name: git-clone
    container:
      image: alpine/git:latest
      command: [sh, -c]
      args:
      - |
        set -e
        echo "📦 Cloning repository..."
        rm -rf /mnt/workspace/* /mnt/workspace/.* 2>/dev/null || true
        git clone {{workflow.parameters.git-repo}} /mnt/workspace
        cd /mnt/workspace
        git checkout {{workflow.parameters.git-branch}}
        GIT_SHA=$(git rev-parse --short HEAD)
        echo "✅ Repository cloned. SHA: $GIT_SHA"
        echo $GIT_SHA > /tmp/git-sha.txt
      volumeMounts:
      - name: workspace-pvc
        mountPath: /mnt/workspace
    outputs:
      parameters:
      - name: git-sha
        valueFrom:
          path: /tmp/git-sha.txt

  - name: kaniko-build-push
    inputs:
      parameters:
      - name: git-sha
      - name: image-version
    container:
      image: gcr.io/kaniko-project/executor:v1.9.1
      args:
      - --dockerfile=/mnt/workspace/Dockerfile
      - --context=dir:///mnt/workspace
      # KEEP EXISTING TAGS SEMANTIC TAGS
      #- --destination=mofwili/easy-nginx:{{inputs.parameters.image-version}}-{{inputs.parameters.git-sha}}
      - --destination=mofwili/easy-nginx:{{inputs.parameters.image-version}}
      #- --destination=mofwili/easy-nginx:latest
      - --cache=false
      - --single-snapshot
      - --verbosity=info
      - --skip-tls-verify
      env:
      - name: DOCKER_CONFIG
        value: /kaniko/.docker
      volumeMounts:
      - name: workspace-pvc
        mountPath: /mnt/workspace
      - name: docker-config
        mountPath: /kaniko/.docker
    outputs:
      parameters:
      #- name: version-tag
        #value: "{{inputs.parameters.image-version}}-{{inputs.parameters.git-sha}}"
      - name: semantic-tag
        value: "{{inputs.parameters.image-version}}"

  - name: security-scan
    inputs:
      parameters:
      - name: image-tag
    container:
      image: aquasec/trivy:latest
      command: [sh, -c]
      args:
      - |
        set -e
        echo "🔒 Starting security scan..."
        echo "📦 Scanning image: {{inputs.parameters.image-tag}}"
        
        # Simple scan without complex output processing
        if trivy image --severity CRITICAL --exit-code 0 {{inputs.parameters.image-tag}}; then
          echo "✅ No critical vulnerabilities found"
          echo "passed" > /tmp/scan-result.txt
        else
          echo "❌ Critical vulnerabilities found"
          echo "failed" > /tmp/scan-result.txt
        fi
        
        echo "📊 Scan completed successfully"
      volumeMounts:
      - name: workspace-pvc
        mountPath: /mnt/workspace
    outputs:
      parameters:
      - name: scan-result
        valueFrom:
          path: /tmp/scan-result.txt

  - name: slack-notification
    inputs:
      parameters:
      - name: status
      - name: message
    container:
      image: curlimages/curl:latest
      command: [sh, -c]
      args:
      - |
        set -e
        echo "📨 Preparing Slack notification..."
        
        if [ -z "$SLACK_WEBHOOK_URL" ]; then
          echo "⚠️  SLACK_WEBHOOK_URL not set, skipping notification"
          exit 0
        fi

        if [ "{{inputs.parameters.status}}" = "success" ]; then
          COLOR="good"
        else
          COLOR="danger"
        fi

        PAYLOAD=$(cat << EOF
        {
          "attachments": [
            {
              "color": "$COLOR",
              "title": "{{inputs.parameters.status}}",
              "text": "{{inputs.parameters.message}}",
              "fields": [
                {
                  "title": "Workflow",
                  "value": "{{workflow.name}}",
                  "short": true
                },
                {
                  "title": "Namespace",
                  "value": "{{workflow.namespace}}",
                  "short": true
                }
              ],
              "footer": "Argo Workflows",
              "ts": $(date +%s)
            }
          ]
        }
        EOF
        )

        echo "📤 Sending Slack notification..."
        curl -X POST \
          -H 'Content-type: application/json' \
          --data "$PAYLOAD" \
          "$SLACK_WEBHOOK_URL"
        
        echo "✅ Notification sent successfully!"
      env:
      - name: SLACK_WEBHOOK_URL
        valueFrom:
          secretKeyRef:
            name: slack-webhook
            key: url

  volumes:
  - name: docker-config
    secret:
      secretName: dockerhub-credentials
      items:
      - key: .dockerconfigjson
        path: config.json

  volumeClaimTemplates:
  - metadata:
      name: workspace-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi