data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: argo
      endpoint: minio.minio:9000
      insecure: true
      accessKeySecret:
        name: minio-secret
        key: accesskey
      secretKeySecret:
        name: minio-secret
        key: secretkey