apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: easy-nginx
  namespace: easy-nginx
  labels:
    app: easy-nginx
  annotations:
    # Argo CD Image Updater annotations
    argocd-image-updater.argoproj.io/image-list: nginx=mofwili/easy-nginx
    argocd-image-updater.argoproj.io/nginx.update-strategy: latest
    argocd-image-updater.argoproj.io/nginx.allow-tags: regexp:^[a-f0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: easy-nginx
  template:
    metadata:
      labels:
        app: easy-nginx
      annotations:
        build.timestamp: "2024-01-01T00:00:00Z"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
      - name: nginx
        image: mofwili/easy-nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: NGINX_ENV
          value: "production"
        - name: COMMIT_SHA
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['argocd-image-updater.argoproj.io/image-tag']
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
  strategy:
    canary:
      # Canary service configuration
      canaryService: easy-nginx-canary
      stableService: easy-nginx
      
      # Traffic routing (using Istio or Service Mesh - we'll use basic canary for now)
      trafficRouting:
        istio:
          virtualService:
            name: easy-nginx-vs
            routes:
            - primary
      
      steps:
      - setWeight: 25
      - pause:
          duration: 30s  # Pause for 30 seconds at 25%
      
      - setWeight: 50
      - pause:
          duration: 30s  # Pause for 30 seconds at 50%
      
      - setWeight: 75
      - pause:
          duration: 20s  # Pause for 20 seconds at 75%
      
      - setWeight: 100
        # Final rollout to 100%