apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: easy-nginx
  namespace: easy-nginx
  labels:
    app: easy-nginx
spec:
  replicas: 2
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: {duration: 10s}
      - setWeight: 50
      - pause: {duration: 10s}
      - setWeight: 75
      - pause: {duration: 10s}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: easy-nginx
  template:
    metadata:
      labels:
        app: easy-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine  # ✅ Use a specific, stable nginx version
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: easy-nginx
  namespace: easy-nginx
spec:
  selector:
    app: easy-nginx
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP